.TH HACKRF_OPERACAKE "1" "July 2021" "hackrf_operacake " "User Commands"
.SH NAME
hackrf_operacake \- control of operacake board via hackrf
.SH DESCRIPTION
.SS "Usage:"
.HP
\fB\-h\fR, \fB\-\-help\fR: this help
.HP
\fB\-d\fR, \fB\-\-device\fR <n>: specify a particular device by serial number
.HP
\fB\-o\fR, \fB\-\-address\fR <n>: specify a particular operacake by address [default: 0x00]
.HP
\fB\-a\fR <n>: set port A connection
.HP
\fB\-b\fR <n>: set port B connection
.HP
\fB\-f\fR <min:max:port>: automatically assign <port> for range <min:max> in MHz
.HP
\fB\-l\fR, \fB\-\-list\fR: list available operacake boards
.HP
\fB\-g\fR, \fB\-\-gpio_test\fR: test GPIO functionality of an opera cake
.SS "Usage:"
.HP
\fB\-h\fR, \fB\-\-help\fR: this help
.HP
\fB\-d\fR, \fB\-\-device\fR <n>: specify a particular device by serial number
.HP
\fB\-o\fR, \fB\-\-address\fR <n>: specify a particular operacake by address [default: 0x00]
.HP
\fB\-a\fR <n>: set port A connection
.HP
\fB\-b\fR <n>: set port B connection
.HP
\fB\-f\fR <min:max:port>: automatically assign <port> for range <min:max> in MHz
.HP
\fB\-l\fR, \fB\-\-list\fR: list available operacake boards
.HP
\fB\-g\fR, \fB\-\-gpio_test\fR: test GPIO functionality of an opera cake
.SH "SEE ALSO"
The primary source of documentation is the wiki on github:

https://github.com/mossmann/hackrf/wiki
