# Hey Emacs, this is a -*- makefile -*-

BINARY = startup_systick_perfo_SPIFI

SRC = startup_systick.c \
	perf_mips.c \
	../common/hackrf_core.c \
	../common/si5351c.c \
	../common/max2837.c

include ../common/Makefile_inc.mk
