#!/bin/sh

echo Program Xilinx CoolRunner-II CPLD on Jellybean, using Bus Blaster v2

jtag <<COMMANDSEND
cable jtagkey vid=0x0403 pid=0x6010 interface=0 driver=ftdi-mpsse
bsdl path bsdl/xc2c
detect
svf default.svf progress stop
COMMANDSEND
